### ISSUE TITLE
CC Container or pod service not launching (dind)

### ISSUE THREAD

**Issue by ravinayag** [npci/falcon#18]
After following the documentation,   Chaincode  container were not able to start after the commit procedure.   Stuck with troubleshooting the current issue..
 Could you share/upload  the Dockerfile for dind  image that used in the peers. 
 Do i need modify the core.yaml for the external chaincode container instantiation ?

Ref Error:
```
Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction 70fbfded9b3aab3c5d9fff59b489375e8c31cd0050f6f33a1bc592832bc95f4c: could not launch chaincode mycc:15aeafc10114a909dcfb5963d50b5a5b371fdf2f9a71afbd966f7896dc92e770: error starting container: error starting container: API error (400): failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"chaincode\": executable file not found in $PATH: unknown"
```

**Comment by tittuvarghese** [comment]
Can you please confirm the below,

1. Version of fabric using
2. Kubernetes Environment (Kubernetes / Rancher / Openshift / GKE / AKS / EKS)
3. Status of dind container under peer
4. Also run the following commands and share the outpur, 
```
kubectl exec -it -n {NAMESPACE} {PEER_NAME} -c dind-daemon -- sh
docker images
docker ps -a
```

**Comment by ravinayag** [comment]
The fabric version i'm using the latest 2.5 over EKS cluster. The dind container  was running with no issues and i was able to see the CC container was up inside the dind service. 

Unfortunetly im not able to reproduce  the above and i strategically moved to CCAAS service methods and its perfectly working now.

we can close this issue. 

I Appreciate and Thank you for all your efforts.

**Comment by tittuvarghese** [comment]
thanks @ravinayag for your response. You are welcome to contribute the CCAAS support to the existing version as well.

**Comment by ravinayag** [comment]
Sure i add up the CCAAS service.
