### ISSUE TITLE
NodePort service 

### ISSUE THREAD

**Issue by Vishva066** [npci/falcon#20]
Do I need to specify a new service for enabling the nodeports. ?? Because when I tried to connect with the endpoint with the curl command it couldn't connect to the pod. My ingress server is up and running. Do I need to change the nodeport service in the services.yaml file?. For establishing this connection The ingress service should be exposed by two Nodeports for Ports: 80/TCP, 443/TCP. Eg; NodePort 30000 => 443/TCP (Ingress service).

If I don't establish the nodeport it is not connecting to the domain using the curl command as mentioned in the falcon docs.

**Comment by siddharthmakwana** [comment]
Yes, as mentioned in pre-requisite you need 
Nginx Ingress OR any other K8S ingress that supports SNI based routing. The ingress service should be exposed by two Nodeports for Ports: 80/TCP, 443/TCP. Eg; NodePort 30000 => 443/TCP (Ingress service).

> Do I need to specify a new service for enabling the nodeports. ?? Because when I tried to connect with the endpoint with the curl command it couldn't connect to the pod. My ingress server is up and running. Do I need to change the nodeport service in the services.yaml file?. For establishing this connection The ingress service should be exposed by two Nodeports for Ports: 80/TCP, 443/TCP. Eg; NodePort 30000 => 443/TCP (Ingress service).
> 
> If I don't establish the nodeport it is not connecting to the domain using the curl command as mentioned in the falcon docs.

Yes, as mentioned in the pre-requisite you need to expose ingress with Nodeport.
_Nginx Ingress OR any other K8S ingress that supports SNI based routing. The ingress service should be exposed by two Nodeports for Ports: 80/TCP, 443/TCP. Eg; NodePort 30000 => 443/TCP (Ingress service)._
